---
title: "Example"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(PanelCurrentStatus)
```

```{r}
data <- readRDS("data.rds")
head(data)
```

```{r}
n <- nrow(data)
delta <- as.matrix(data[, 1:5])
ctime <- as.matrix(data[, 5 + 1:5])
predictors <- as.matrix(data[, 10 + 1:3])
```

Calcuate the scaled coefficients from the conditional censoring logistic (CCL) estimator 

```{r}
fit <- ccl.fit(delta, ctime, predictors, n.ptb = 500, seed = 1)
data.frame(est = fit[[2]], est.se = fit[[3]])
```

Prepare the data for evaluating the model metrics from ROC curve via kernel smoothing

```{r, warning=FALSE}
alldata <- NULL
for (k in 1:ncol(delta)) {
  DF <- data.frame(delta = delta[, k], ctime = ctime[, k], predictors)
  alldata <- rbind(alldata, DF)
}
t0 <- median(alldata$ctime)
h <- sd(alldata$ctime) / n^0.3
ans <- ccl.roc(alldata, fit, t0, h)
data.frame(roc = ans[[1]], roc.se = ans[[2]])
```

```{r}
proc.time()
```
